config/routes.rb
Rails.application.routes.draw do
  resources :perguntas_assessjur2s
  resources :perguntas_assessjurs
  root to: "perguntas_assessjurs#index"
  get "novp/:id", to: 'perguntas_assessjurs#new'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/perguntas_assessjur.rb
class PerguntasAssessjur < ApplicationRecord
end

app/models/perguntas_assessjur2.rb
class PerguntasAssessjur2 < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/perguntas_assessjur2s_controller.rb
class PerguntasAssessjur2sController < ApplicationController
  before_action :set_perguntas_assessjur2, only: %i[ show edit update destroy ]

  # GET /perguntas_assessjur2s or /perguntas_assessjur2s.json
  def index
    @perguntas_assessjur2s = PerguntasAssessjur2.all
  end

  # GET /perguntas_assessjur2s/1 or /perguntas_assessjur2s/1.json
  def show
  end

  # GET /perguntas_assessjur2s/new
  def new
    @perguntas_assessjur2 = PerguntasAssessjur2.new
  end

  # GET /perguntas_assessjur2s/1/edit
  def edit
  end

  # POST /perguntas_assessjur2s or /perguntas_assessjur2s.json
  def create
    @perguntas_assessjur2 = PerguntasAssessjur2.new(perguntas_assessjur2_params)

    respond_to do |format|
      if @perguntas_assessjur2.save
        format.html { redirect_to perguntas_assessjur2_url(@perguntas_assessjur2), notice: "Perguntas assessjur2 was successfully created." }
        format.json { render :show, status: :created, location: @perguntas_assessjur2 }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @perguntas_assessjur2.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /perguntas_assessjur2s/1 or /perguntas_assessjur2s/1.json
  def update
    respond_to do |format|
      if @perguntas_assessjur2.update(perguntas_assessjur2_params)
        format.html { redirect_to perguntas_assessjur2_url(@perguntas_assessjur2), notice: "Perguntas assessjur2 was successfully updated." }
        format.json { render :show, status: :ok, location: @perguntas_assessjur2 }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @perguntas_assessjur2.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /perguntas_assessjur2s/1 or /perguntas_assessjur2s/1.json
  def destroy
    @perguntas_assessjur2.destroy

    respond_to do |format|
      format.html { redirect_to perguntas_assessjur2s_url, notice: "Perguntas assessjur2 was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_perguntas_assessjur2
      @perguntas_assessjur2 = PerguntasAssessjur2.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def perguntas_assessjur2_params
      params.require(:perguntas_assessjur2).permit(:duvida, :tel, :email, :tp_duvida, :status, :numatd)
    end
end

app/controllers/perguntas_assessjurs_controller.rb
class PerguntasAssessjursController < ApplicationController
  before_action :set_perguntas_assessjur, only: %i[ show edit update destroy]

  # GET /perguntas_assessjurs or /perguntas_assessjurs.json
  def index
    @perguntas_assessjurs = PerguntasAssessjur.all
  end

  # GET /perguntas_assessjurs/1 or /perguntas_assessjurs/1.json
  def show
  end

  # GET /perguntas_assessjurs/new
  def new
    @perguntas_assessjur = PerguntasAssessjur.new
    @pjur = ""
    @criar  = true
    if params.has_key?(params[:id])
      @pjur = PerguntasAssessjur.where(id: params[:id])
      @s = "aqui"
    elsif PerguntasAssessjur.count > 0
      @pjur = PerguntasAssessjur.order("id DESC");
      @pjur = @pjur[0]["created_at"]
      @s = "no"
    end
    
    @count = PerguntasAssessjur.all.count
  end

  # GET /perguntas_assessjurs/1/edit
  def edit
    @pjur = ""
    @criar = false
  end

  # POST /perguntas_assessjurs or /perguntas_assessjurs.json
  def create
    @perguntas_assessjur = PerguntasAssessjur.new(perguntas_assessjur_params)

   
    respond_to do |format|
      if @perguntas_assessjur.save
        format.html { redirect_to perguntas_assessjur_url(@perguntas_assessjur), notice: "Perguntas assessjur was successfully created." }
        format.json { render :show, status: :created, location: @perguntas_assessjur }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @perguntas_assessjur.errors, status: :unprocessable_entity }
      end
    end
   
  end

  # PATCH/PUT /perguntas_assessjurs/1 or /perguntas_assessjurs/1.json
  def update
    respond_to do |format|
      if @perguntas_assessjur.update(perguntas_assessjur_params)
        format.html { redirect_to perguntas_assessjur_url(@perguntas_assessjur), notice: "Perguntas assessjur was successfully updated." }
        format.json { render :show, status: :ok, location: @perguntas_assessjur }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @perguntas_assessjur.errors, status: :unprocessable_entity }
      end
    end
  end

 

  # DELETE /perguntas_assessjurs/1 or /perguntas_assessjurs/1.json
  def destroy
    @perguntas_assessjur.destroy

    respond_to do |format|
      format.html { redirect_to perguntas_assessjurs_url, notice: "Perguntas assessjur was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_perguntas_assessjur
      @perguntas_assessjur = PerguntasAssessjur.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def perguntas_assessjur_params
      params.require(:perguntas_assessjur).permit(:duvida, :tel, :email, :tp_duvida, :status, :numatd)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def gerarNumAtd(count, diaDb)
        # pegando o dia atual
        diaAtual = Time.new
        getDiaDb = diaDb

        diaAtual = "#{diaAtual.day}#{diaAtual.month}#{diaAtual.year}"
        getDiaDb = "#{getDiaDb.day}#{getDiaDb.month}#{getDiaDb.year}"

        if diaAtual == getDiaDb
            diaAtual = diaDb
            num = count + 1
        else
            diaAtual = Time.new
            num = 0 + 1
        end
       
        diaAtual = diaDb
        dia = diaAtual.day
        mes = diaAtual.month
        if mes < 10
            mes = "0#{mes}"
        end
        ano = diaAtual.year
        
        num_atd = num.to_s.rjust(5,'0')

        "#{ano}#{mes}#{dia}#{num_atd}"
    end
end

app/helpers/perguntas_assessjur2s_helper.rb
module PerguntasAssessjur2sHelper
end

app/helpers/perguntas_assessjurs_helper.rb
module PerguntasAssessjursHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AssessoriaJuridicaTeste</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/perguntas_assessjur2s/_form.html.erb
<%= form_with(model: perguntas_assessjur2) do |form| %>
  <% if perguntas_assessjur2.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(perguntas_assessjur2.errors.count, "error") %> prohibited this perguntas_assessjur2 from being saved:</h2>

      <ul>
        <% perguntas_assessjur2.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :duvida %>
    <%= form.text_field :duvida %>
  </div>

  <div class="field">
    <%= form.label :tel %>
    <%= form.text_field :tel %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :tp_duvida %>
    <%= form.text_field :tp_duvida %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="field">
    <%= form.label :numatd %>
    <%= form.text_field :numatd %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/perguntas_assessjur2s/edit.html.erb
<h1>Editing Perguntas Assessjur2</h1>

<%= render 'form', perguntas_assessjur2: @perguntas_assessjur2 %>

<%= link_to 'Show', @perguntas_assessjur2 %> |
<%= link_to 'Back', perguntas_assessjur2s_path %>

app/views/perguntas_assessjur2s/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Perguntas Assessjur2s</h1>

<table>
  <thead>
    <tr>
      <th>Duvida</th>
      <th>Tel</th>
      <th>Email</th>
      <th>Tp duvida</th>
      <th>Status</th>
      <th>Numatd</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @perguntas_assessjur2s.each do |perguntas_assessjur2| %>
      <tr>
        <td><%= perguntas_assessjur2.duvida %></td>
        <td><%= perguntas_assessjur2.tel %></td>
        <td><%= perguntas_assessjur2.email %></td>
        <td><%= perguntas_assessjur2.tp_duvida %></td>
        <td><%= perguntas_assessjur2.status %></td>
        <td><%= perguntas_assessjur2.numatd %></td>
        <td><%= link_to 'Show', perguntas_assessjur2 %></td>
        <td><%= link_to 'Edit', edit_perguntas_assessjur2_path(perguntas_assessjur2) %></td>
        <td><%= link_to 'Destroy', perguntas_assessjur2, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Perguntas Assessjur2', new_perguntas_assessjur2_path %>

app/views/perguntas_assessjur2s/new.html.erb
<h1>New Perguntas Assessjur2</h1>

<%= render 'form', perguntas_assessjur2: @perguntas_assessjur2 %>

<%= link_to 'Back', perguntas_assessjur2s_path %>

app/views/perguntas_assessjur2s/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Duvida:</strong>
  <%= @perguntas_assessjur2.duvida %>
</p>

<p>
  <strong>Tel:</strong>
  <%= @perguntas_assessjur2.tel %>
</p>

<p>
  <strong>Email:</strong>
  <%= @perguntas_assessjur2.email %>
</p>

<p>
  <strong>Tp duvida:</strong>
  <%= @perguntas_assessjur2.tp_duvida %>
</p>

<p>
  <strong>Status:</strong>
  <%= @perguntas_assessjur2.status %>
</p>

<p>
  <strong>Numatd:</strong>
  <%= @perguntas_assessjur2.numatd %>
</p>

<%= link_to 'Edit', edit_perguntas_assessjur2_path(@perguntas_assessjur2) %> |
<%= link_to 'Back', perguntas_assessjur2s_path %>

app/views/perguntas_assessjurs/_form.html.erb
<%= form_with(model: perguntas_assessjur) do |form| %>
  <% if perguntas_assessjur.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(perguntas_assessjur.errors.count, "error") %> prohibited this perguntas_assessjur from being saved:</h2>

      <ul>
        <% perguntas_assessjur.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :duvida %>
    <%= form.text_area :duvida %>
  </div>

  <div class="field">
    <%= form.label :tel %>
    <%= form.text_field :tel %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :tp_duvida %>
    <%= form.text_field :tp_duvida %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="field">
    <%= form.label :numatd %>
    <% if @criar %>
      <%= form.text_field :numatd, value:"#{gerarNumAtd(@count, @pjur)}"%>
    <% else %>
      <%= form.text_field :numatd %>
    <% end %>
  </div>
  <%= @s %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/perguntas_assessjurs/edit.html.erb
<h1>Editing Perguntas Assessjur</h1>

<%= render 'form', perguntas_assessjur: @perguntas_assessjur %>

<%= link_to 'Show', @perguntas_assessjur %> |
<%= link_to 'Back', perguntas_assessjurs_path %>

app/views/perguntas_assessjurs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Perguntas Assessjurs</h1>

<table>
  <thead>
    <tr>
      <th>Duvida</th>
      <th>Tel</th>
      <th>Email</th>
      <th>Tp duvida</th>
      <th>Status</th>
      <th>Numatd</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @perguntas_assessjurs.each do |perguntas_assessjur| %>
      <tr>
        <td><%= perguntas_assessjur.duvida %></td>
        <td><%= perguntas_assessjur.tel %></td>
        <td><%= perguntas_assessjur.email %></td>
        <td><%= perguntas_assessjur.tp_duvida %></td>
        <td><%= perguntas_assessjur.status %></td>
        <td><%= perguntas_assessjur.numatd %></td>
        <td><%= link_to 'Show', perguntas_assessjur %></td>
        <td><%= link_to 'Edit', edit_perguntas_assessjur_path(perguntas_assessjur) %></td>
        <td><%= link_to 'cadastrar pergunta em mesmo atendimento', "novp/#{perguntas_assessjur.id}" %></td>
        <td><%= link_to 'Destroy', perguntas_assessjur, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to 'New Perguntas Assessjur', new_perguntas_assessjur_path %>

app/views/perguntas_assessjurs/new.html.erb
<h1>New Perguntas Assessjur</h1>

<%= render 'form', perguntas_assessjur: @perguntas_assessjur %>

<%= link_to 'Back', perguntas_assessjurs_path %>

app/views/perguntas_assessjurs/novop.html.erb
<h1>Nova Perguntas Assessjur</h1>

<%= render 'form', perguntas_assessjur: @perguntas_assessjur %>

<%= link_to 'Back', perguntas_assessjurs_path %>

app/views/perguntas_assessjurs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Duvida:</strong>
  <%= @perguntas_assessjur.duvida %>
</p>

<p>
  <strong>Tel:</strong>
  <%= @perguntas_assessjur.tel %>
</p>

<p>
  <strong>Email:</strong>
  <%= @perguntas_assessjur.email %>
</p>

<p>
  <strong>Tp duvida:</strong>
  <%= @perguntas_assessjur.tp_duvida %>
</p>

<p>
  <strong>Status:</strong>
  <%= @perguntas_assessjur.status %>
</p>

<p>
  <strong>Numatd:</strong>
  <%= @perguntas_assessjur.numatd %>
</p>

<%= link_to 'Edit', edit_perguntas_assessjur_path(@perguntas_assessjur) %> |
<%= link_to 'Back', perguntas_assessjurs_path %>